### ISSUE TITLE
Ability to copy `cdylib` and `rlib` artifacts back to original target folder

### ISSUE THREAD

**Issue by edgimar** [asaaki/wargo#109]
## Feature Request

The `wargo` tool currently only copies artifacts with a `bin` target kind, which means that it will not copy `cdylib` or `rlib` kinds.  It would be great if it were also possible to also copy back these kinds of artifacts, either via a configuration option, or by default.

**Comment by asaaki** [comment]
I merged your PR and released version 0.3.0 to crates.io registry.

Happy WSL compiling! 🎉
